#!/usr/bin/env bash

function msg
{
    echo -e "\033[32mFRI Builder:\033[0m \033[35m$@\033[0m"
}

function err
{
    echo -e "\033[31mFRI Builder: $@\033[0m"
}

msg "Working in $(pwd)"

declare conf_file="FileResourceIntegration.conf"

conf="resources/generated/${conf_file}"
conf_temp="resources/generated/fri_builder_preproc_conf"
target_c_file="resources/generated/dynamic_buildtime_fri.c"

if [[ ! -f "$conf" ]]; then
    err "Couldn't find configuration file"
    exit 1
fi

sed -E '/^#+.*$/d' $conf >$conf_temp
echo >>$conf_temp

## Write header and comments
cat >$target_c_file <<EOF
/**
 * This file is generated by FRI Builder. It's a part of cocoa project.
 * Don't edit it or delete it. Update it through running the script
 * at tools/FileResourceIntegration.sh or reconfiguring CMake.
 */

/* Import some necessary macros and declarations */
#include "Buildtime.h"

EOF

function generate
{
    local file=$1
    local sym=$2

    if [[ ! -f $file ]]; then
        err "No such file ($file)"
        return 1
    fi

    echo "/* From file $file */" >>$target_c_file
    echo "DEFINE_FILE_INTEGRATION_STRING($sym) = \"\\" >>$target_c_file
    cat $file | while read line; do
        proced=$(echo "$line" | sed -e 's/\\/\\\\/g' -e 's/\"/\\\"/g')
        echo "$proced\\n\\" >>$target_c_file
    done

    echo "\";" >> $target_c_file
    echo >>$target_c_file

    msg "Generated for $file"
}

cat $conf_temp | while read line; do
    if [[ "x$line" = "x" ]]; then continue; fi
    generate $line
done

rm $conf_temp
exit 0
